# Generated by Django 4.1.5 on 2023-01-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=50, verbose_name='Название')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('task', models.TextField(verbose_name='Описание')),
                ('text', models.TextField(verbose_name='Содержание')),
            ],
        ),
    ]
