# Generated by Django 4.1.5 on 2023-01-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='titles',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='age',
        ),
    ]
